### ISSUE TITLE
Send Test Message gets an error

### ISSUE THREAD

**Issue by mgmaik** [igniter-labs/ti-ext-smsnotify#12]
**Expected behavior:**
Sending a test text message to the store phone number

**Actual behavior:**
Getting an error message: "Missing config. You must set either the username & password or SID and auth token"

System log:
NotificationChannels\Twilio\Exceptions\InvalidConfigException: Missing config. You must set either the username & password or SID and auth token
in /var/www/vhosts/theshakery.nl/order.theshakery.nl/extensions/igniterlabs/smsnotify/vendor/laravel-notification-channels/twilio/src/Exceptions/InvalidConfigException.php:11

**Reproduce steps:**
Installed SMS Notify, signed up to Twillio and configured phone number then added an account SID, Auth Token and Number
Set as default and enabled.

Opened up SMS Templates page and pressed the Send Test Message button. 

**Version:**
TI version 3.2.0.

**Additional Information:**
SMS Notify    v2.1.1

**Comment by martin-ro** [comment]
Same issue for me

**Comment by martin-ro** [comment]
I just got it working by adding 

TWILIO_AUTH_TOKEN=xxx
TWILIO_ACCOUNT_SID=xxx

to my .env

**Comment by mgmaik** [comment]
That seems to work! 

Also not forgetting to add 
TWILIO_FROM=XXX

**Comment by sampoyigi** [comment]
Fixed https://github.com/igniter-labs/ti-ext-smsnotify/commit/7a96fc19243d53c00497b49b4fca1b40b2163ef9
