### ISSUE TITLE
Cannot declare class Nexmo\Client, because the name is already in use

### ISSUE THREAD

**Issue by myrsk** [igniter-labs/ti-ext-smsnotify#13]
**Expected behavior:**
To be able to send out an sms via Nexmo/Vonage 

**Actual behavior:**
I've just tried with Nexmo/Vonage, and in the recent failures tab in the automation I am getting the below

DATE | STATUS | ACTION | MESSAGE
-- | -- | -- | --
43 seconds ago | Failed | -- | Cannot declare class Nexmo\Client, because the name is already in use
-- | -- | -- | --

**Reproduce steps:**
Add API settings of Nexmo/Vonage, and send out an SMS

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.

**Comment by myrsk** [comment]
This still exists unfortunately. 

Regards

**Comment by sampoyigi** [comment]
Just pushed a new release that drops laravel notifications and use SDK directly.
