### ISSUE TITLE
Cannot send via Nexmo/Vonage

### ISSUE THREAD

**Issue by roydeanjr** [igniter-labs/ti-ext-smsnotify#6]
Configuration page worked fine.
Attempt to send and get this in error log: ErrorException: Cannot declare class Nexmo\Client, because the name is already
in use in /home/ardeec92/public_html/extensions/igniterlabs/smsnotify/vendor/vonage/nexmo-bridge/src/Autoloader.php:159

Never received a txt message.

Same error occurs when attempting to send a test message via the Send Test Message button on the SMS Templage update page.

**Comment by sampoyigi** [comment]
I am unable to reproduce this

**Comment by roydeanjr** [comment]
I cannot get the latest fixes installed to test so I don't know if you have fixed this one or not.

BTW, what is the exact procedure to get your latest fixes installed on beta.23.2? I tried to upload the developer branch and the cart and reservation extensions to a working 23.2 site and the site got hosed so much that I had to restore to 23.2. Thus I cannot test the fixes you have committed.

**Comment by sampoyigi** [comment]
Check out the docs https://tastyigniter.com/docs/master/contribution-guide#development-setup

**Comment by AyFun** [comment]
Same error.

**Comment by sampoyigi** [comment]
Fixed

**Comment by myrsk** [comment]
I've just tried with Nexmo/Vonage, and in the recent failures tab in the automation I am getting the below


DATE | STATUS | ACTION | MESSAGE
-- | -- | -- | --
43 seconds ago | Failed | -- | Cannot declare class Nexmo\Client, because the name is already in use
-- | -- | -- | --

Any ideas? v2.1.3
