### ISSUE TITLE
Status is incorrect.

### ISSUE THREAD

**Issue by roydeanjr** [igniter-labs/ti-ext-smsnotify#7]
The status for the SMS message is incorrect. The status for the email is correct. The SMS message is exactly opposite to the status I toggled. For instance, when I click Preparation I get a message that the order is Ready. When I click Ready I get a message that the order is in Preparation.

This is using the Twilio channel. That channel I was able to get working without any issues.

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.
