### ISSUE TITLE
SMS Not sending when status is updated

### ISSUE THREAD

**Issue by roydeanjr** [igniter-labs/ti-ext-smsnotify#8]
v1.0.3 is not sending sms when the status of an order changes.
I have tried numerous times to effect a different outcome, however, even after installing the master, the SMS Notify extension is not sending messages. Nor is it producing any error. It will send a test message using twilio, but not any of the other channels.

It seems like the Automation is never triggered.

**Comment by sampoyigi** [comment]
I've updated the extension to throw an error.

**Comment by roydeanjr** [comment]
Ok, I installed v1.0.4 and still no message being sent when status changes.

Where is the error supposed to appear? 
When I change the status on the orders page, I do not get an sms, but I do get an email.
When I change the status on the Kitchen Display extension I go not get an sms, but I do get an email.

**Comment by sampoyigi** [comment]
If you try the test message, you should see an error.

**Comment by roydeanjr** [comment]
I see. I believe I did that. The test message sends just fine. The status change is not triggering an sms message anymore. It did for a while, but then after the 1.0.1 or .2 updates it no longer sent a message.

**Comment by roydeanjr** [comment]
Also, the database igniterlabs_smsnotify_logs is not showing any entries. Shouldn't it have records for each message sent or is that a temp table for the message that is queued to go out?

**Comment by sampoyigi** [comment]
What version of the automation extension are you using? `igniterlabs_smsnotify_logs` is no longer used and will be removed at some point

**Comment by roydeanjr** [comment]
I am using v1.1.2 of Automation.

**Comment by sampoyigi** [comment]
Yup, best to always update extensions to their latest version. 

I just tagged v1.1.4 which adds task logging to automation actions.

**Comment by roydeanjr** [comment]
Perfect. Is it an update on marketplace or just github?

**Comment by roydeanjr** [comment]
I see it on markeplace, but it is not getting flagged as an update that needs to be installed.

**Comment by roydeanjr** [comment]
Oops! Got this when installing: 
{ "message": "system::lang.missing.config_key", "exception": "Igniter\\Flame\\Exception\\SystemException", "file": "/home/ardeec92/public_html/app/system/classes/BaseExtension.php", "line": 195, "trace": [ { "file": "/home/ardeec92/public_html/app/system/classes/BaseExtension.php", "line": 51, "function": "getConfigFromFile", "class": "System\\Classes\\BaseExtension", "type": "->" }, { "file": "/home/ardeec92/public_html/app/system/classes/ExtensionManager.php", "line": 258, "function": "extensionMeta", "class": "System\\Classes\\BaseExtension", "type": "->" }, { "file": "/home/ardeec92/public_html/app/system/classes/ExtensionManager.php", "line": 230, "function": "getDependencies", "class": "System\\Classes\\ExtensionManager", "type": "->" }, { "file": "/home/ardeec92/public_html/app/system/classes/ExtensionManager.php", "line": 73, "function": "loadDependencies", "class": "System\\Classes\\ExtensionManager", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/tastyigniter/flame/src/Traits/Singleton.php", "line": 30, "function": "initialize", "class": "System\\Classes\\ExtensionManager", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/tastyigniter/flame/src/Traits/Singleton.php", "line": 22, "function": "__construct", "class": "System\\Classes\\ExtensionManager", "type": "->" }, { "file": "/home/ardeec92/public_html/app/system/ServiceProvider.php", "line": 57, "function": "instance", "class": "System\\Classes\\ExtensionManager", "type": "::" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php", "line": 616, "function": "register", "class": "System\\ServiceProvider", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php", "line": 75, "function": "register", "class": "Illuminate\\Foundation\\Application", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php", "line": 593, "function": "load", "class": "Illuminate\\Foundation\\ProviderRepository", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php", "line": 17, "function": "registerConfiguredProviders", "class": "Illuminate\\Foundation\\Application", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php", "line": 219, "function": "bootstrap", "class": "Illuminate\\Foundation\\Bootstrap\\RegisterProviders", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 156, "function": "bootstrapWith", "class": "Illuminate\\Foundation\\Application", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 140, "function": "bootstrap", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "/home/ardeec92/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", "line": 110, "function": "sendRequestThroughRouter", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" }, { "file": "/home/ardeec92/public_html/index.php", "line": 53, "function": "handle", "class": "Illuminate\\Foundation\\Http\\Kernel", "type": "->" } ] }

**Comment by roydeanjr** [comment]
Now browsing more extensions if erroring out with `system::lang.missing.config_key`

**Comment by sampoyigi** [comment]
Ah! My bad. I keep screwing up lol. I should not have removed the version string from the extension meta-file... 

Tagged v1.1.6

**Comment by sampoyigi** [comment]
Available on the marketplace

**Comment by roydeanjr** [comment]
Ouch! That's a major break and the only fix is to ftp the extension back to the site.....

**Comment by roydeanjr** [comment]
Interesting......Task log shows Success, Action performed successfully. Now to twilio and there is not a record of the message ever being received by twilio......
