### ISSUE TITLE
Add notification channel for bandwidth

### ISSUE THREAD

**Issue by roydeanjr** [igniter-labs/ti-ext-smsnotify#9]
Would it be possible to add support for bandwidth?

Here is an archived channel package. Not sure why it is archived: https://github.com/ankurk91/bandwidth-notification-channel. I have tagged the author in another issue in the laravel-notification-channels repo. @ankurk91

**Comment by roydeanjr** [comment]
Referenced here: https://github.com/laravel-notification-channels/channels/issues/111

**Comment by sampoyigi** [comment]
Seems you've already done some research on the channel. I'm happy to integrate with this extension if others will find it useful... Maybe ask on the forum?

**Comment by roydeanjr** [comment]
Some research, but not enough. Turns out that my business is too small for bandwidth. I was referred to other providers rather than taken on as a bandwidth customer. I am closing this request as it does not do me any good to develop or support.
